# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78398ebb04815c5893e2cd3bf1883f7b8b240d924cb51d81bb115dc3d09bdc1c1fbe93210504bbd65d2d59d08b35ec29d6f7f2732b141c563d4c94722753e62b

test:
  secret_key_base: 7648a073c5b8cb028900324d4d41914e898e9d72f19c3f2061cbf28c9a7e46d622cac0a110d2e9078e3656af1c33d26e713492399b70a0daf2b8b061330bac69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
